name: Testar Notebook de Análise de Acidentes

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você preferir
  pull_request:
    branches:
      - main

jobs:
  test_notebook:
    runs-on: ubuntu-latest  # Sistema operacional que será usado para rodar o job

    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v2  # Faz o checkout do código do repositório

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Versão do Python que você está usando
          
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt  # Instala as dependências do requirements.txt


      - name: Instalar Jupyter
        run: pip install notebook  # Instala o Jupyter Notebook, caso não esteja no requirements.txt

      - name: Testar o Notebook
        run: |
          jupyter nbconvert --to notebook --execute notebooks/analise_acidentes.ipynb --output result_notebook.ipynb
          # A execução do notebook será salva no arquivo result_notebook.ipynb
